### ISSUE TITLE
Criar template padrão das páginas

### ISSUE THREAD

**Issue by MarcosNBJ** [ArticaDev/cinema-podcasts#1]
Criar markup e estilização do template padrão das páginas de acordo com o protótipo.

## Critérios de aceitação 
- [x] Barra de navegação
- [x] Rodapé 
- [x] Design padrão de tipografia
- [x] Design padrão do body

**Comment by LLxD** [comment]
O protótipo não tem rodapé, o que fazer?

**Comment by LLxD** [comment]
Terminei o footer, verifica lá depois meu bom!

**Comment by MarcosNBJ** [comment]
Issue cumprida no [PR da branch feature/footer](https://github.com/ArticaDev/cinema-podcasts/pull/12)
